FROM alpine:3.18.6
LABEL wlrm=check
ENV WALLARM_API='api.wallarm.com' \
    USER_UID=1001
WORKDIR /etc/wlrm
COPY bin/linux/w /bin/wlrm
COPY domains.conf /etc/wlrm/domains.conf
USER ${USER_UID}
CMD ["wlrm"]