apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}.wapi.creds
type: Opaque
data:
  wallarm_uuid: {{ .Values.wallarm_uuid | b64enc }}
  wallarm_secret: {{ .Values.wallarm_secret | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}.telegram.creds
type: Opaque
data:
  telegram_token: {{ .Values.telegram_token | b64enc }}
  chat_id: {{ .Values.chat_id | toString | b64enc }}